metadata/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>This object is related to the GRAX Schedule Process Object. These records contain the object and relationship to the Salesforce record(s) which will be backed up/archived from Salesforce.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Error_Message</description>
        <inlineHelpText>Description of the Error message received</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_SFObject_Process_End_Time__c</fullName>
        <description>Overall SFObject Process End Time</description>
        <label>Overall SFObject Process End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Overall_SFObject_Process_Start_Time__c</fullName>
        <description>Overall SFObject Process Start Time</description>
        <label>Overall SFObject Process Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>Salesforce_Object</description>
        <inlineHelpText>Name of Salesforce object which is being backed up</inlineHelpText>
        <label>Salesforce Object</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Times_Sent__c</fullName>
        <description>of_Times_Sent</description>
        <label># of Times Sent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Archive</description>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Run_Date__c</fullName>
        <description>Last_Run_Date</description>
        <inlineHelpText>Last time this Scheduled Process was run</inlineHelpText>
        <label>Last Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object_Name</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progressive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Progressive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Notifications__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Notifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors sending data</fullName>
                </value>
                <value>
                    <fullName>Sending data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Deleting Salesforce records</fullName>
                </value>
                <value>
                    <fullName>Pending send data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors deleting records</fullName>
                </value>
                <value>
                    <fullName>Starting Archive Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hierarchy</fullName>
                    <default>true</default>
                    <label>Hierarchy</label>
                </value>
                <value>
                    <fullName>Multi-Object</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXBackupSummaryTest.cls
@isTest
private class GRAXBackupSummaryTest {
	@isTest
	static void GRAXBackupSummaryTest1() {
		Integer testRecordsSize = 2;
        
        List<GRAX_Schedule_Process__c> gspList = new List<GRAX_Schedule_Process__c>();

        for(Integer i = 0; i < testRecordsSize; i++) {
            GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();

            gsp.Object_Name__c = 'GRAX_Schedule_Process__c';
            gsp.Progressive__c = false;
            gsp.Start_Time__c = Datetime.now();
            gsp.Last_Run_Date__c = Datetime.now().addMinutes(2);
            gsp.Status__c = 'Completed';
            gsp.Execution_Unique_Key__c = 'testest' + String.valueOf(i);

            if(Math.mod(i, 2) == 0) {
                gsp.Archive__c = true;
                gsp.Send_Notifications__c = true;
                gsp.type__c = 'Hierarchy';
            } else {
                gsp.Archive__c = false;
                gsp.Send_Notifications__c = false;
                gsp.type__c = 'Multi-Object';
            }

            gspList.add(gsp);
        }

        insert gspList;


        List<GRAX_Data_Record__c> drList = new List<GRAX_Data_Record__c>();

        for(GRAX_Schedule_Process__c gsp : gspList) {
            GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
            dr.Salesforce_Object__c = gsp.Object_Name__c;
            dr.Status__c = 'Sent Successful';
            dr.of_Times_Sent__c = 1;
            dr.Error_Message__c = null;
            dr.Overall_SFObject_Process_Start_Time__c = Datetime.now().addMinutes(-1);
            dr.Overall_SFObject_Process_End_Time__c = dr.Overall_SFObject_Process_Start_Time__c.addMinutes(2);
            dr.Execution_Unique_Key__c = gsp.Execution_Unique_Key__c;

            drList.add(dr);
        }

        insert drList;

        System.assert(GRAXBackupSummary.summariesList == null);

        for(GRAX_Schedule_Process__c gsp : gspList) {
            GRAXBackupSummary.generateExecutionSummary(gsp.Id, gsp.Execution_Unique_Key__c);
        }

        System.assert(GRAXBackupSummary.summariesList <> null);
        System.assert(GRAXBackupSummary.summariesList.size() == testRecordsSize);

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, 'OK', '{}', null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        System.assert(GRAXBackupSummary.summariesList <> null);
        System.assert(GRAXBackupSummary.summariesList.size() == testRecordsSize);

        Test.startTest();

        GRAXBackupSummary.sendSummaries();

        Test.stopTest();

        System.assert(GRAXBackupSummary.summariesList.size() == 0);
	}
}