metadata/objects/GRAX_Archive_Process__c.object
<CustomObject>
    <description>This object is used when the user creates a &quot;Scheduled Process&quot; and decides to Archive records from Salesforce.</description>
    <fields>
        <fullName>Async_Records_Successfully_Sent__c</fullName>
        <label># Async Records Successfully Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Async_Records_to_Process__c</fullName>
        <label># Async Records to Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_Successfully_Sent__c</fullName>
        <label># Records Successfully Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_To_Process__c</fullName>
        <description>Count of the # of records which have been processed within Salesforce</description>
        <label># Records To Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_SFDC_Records_Deleted__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Total SFDC Records Deleted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_SFDC_Records_Failed_to_Delete__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Total SFDC Records Failed to Delete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_SFDC_Records__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Total SFDC Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GRAX Archive Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Archive Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Archive Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/classes/GRAXArchiveProcessTriggerHandler.cls
/*****************************************************************************************
Name              : GRAXArchiveProcessTriggerHandler
Description       : -
Revision History  :
Created/Modified by   Created/Modified Date     Requested by          Related Task/Issue             
----------------------------------------------------------------------------------------
1. Ariel Yankelevich       06/06/2018           David Mackey        Backup and Restore Notes & Attachments (https://app.asana.com/0/326600806074978/692982800286805/f)
******************************************************************************************/

public with sharing class GRAXArchiveProcessTriggerHandler {
	
    public static void triggerExecute(){        
        if(Trigger.isBefore){
        	if(Trigger.isUpdate){
                summarizeRollupFields();  
        	}           
        }
    }
    
    
    /*******************************************************************************
    Name              : summarizeRollupFields
    Description       : This trigger summarizes the rollup fields on the GRAX_Archive_Process__c record
    Events            : before update
    Revision History  : - 
    Created/Modified by   Created/Modified Date     Requested by          Related Task/Issue  
    ----------------------------------------------------------------------------------------
    1. Ariel Yankelevich       06/06/2018           David Mackey        Backup and Restore Notes & Attachments (https://app.asana.com/0/326600806074978/692982800286805/f)
	*******************************************************************************/
    
    public static void summarizeRollupFields(){
        Set<String> rollupFields = new Set<String>{'Async_Records_Successfully_Sent__c', 'Async_Records_to_Process__c', 'Records_Successfully_Sent__c', 'Records_To_Process__c', 'Total_SFDC_Records__c', 'Total_SFDC_Records_Deleted__c', 'Total_SFDC_Records_Failed_to_Delete__c'};
        
        for(Integer i = 0; i < Trigger.size; i++){
            for(String fieldName : rollupFields){
                if(GRAXDataRecordTriggerHandler.GRAXArchiveProcRollupFields.contains(fieldName)){
                    Trigger.new[i].put(fieldName, (Double)Trigger.new[i].get(fieldName) + (Double)Trigger.old[i].get(fieldName));
                }
            }
        }
    }
}