metadata/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>This object is related to the GRAX Schedule Process Object. These records contain the object and relationship to the Salesforce record(s) which will be backed up/archived from Salesforce.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_SFObject_Process_End_Time__c</fullName>
        <description>Overall SFObject Process End Time</description>
        <label>Overall SFObject Process End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Overall_SFObject_Process_Start_Time__c</fullName>
        <description>Overall SFObject Process Start Time</description>
        <label>Overall SFObject Process Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>Salesforce_Object</description>
        <inlineHelpText>Name of Salesforce object which is being backed up</inlineHelpText>
        <label>Salesforce Object</label>
        <type>TextArea</type>
    </fields>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Archive</description>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Run_Date__c</fullName>
        <description>Last_Run_Date</description>
        <inlineHelpText>Last time this Scheduled Process was run</inlineHelpText>
        <label>Last Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object_Name</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progressive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Progressive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Notifications__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Notifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hierarchy</fullName>
                    <default>true</default>
                    <label>Hierarchy</label>
                </value>
                <value>
                    <fullName>Multi-Object</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXBackupSummary.cls
/*****************************************************************************************
Name              : GRAXBackupSummary
Description       : Do a callout to GRAX, generate a summary of a specific Execution Key and save it on Elastic.
Revision History  :
Created/Modified by   Created/Modified Date     Requested by          Related Task/Issue             
----------------------------------------------------------------------------------------
1. Leandro Brunner			02/28/2019			David Mackey		Review "Backup Stats" (https://app.asana.com/0/326600806074978/1107778902588819/f)
******************************************************************************************/
public with sharing class GRAXBackupSummary {
    public GRAXBackupSummary() {}
    
    public static List<Map<String, Object>> summariesList;

    public static void generateExecutionSummary(String gspId, String executionUniqueKey) {
        if(summariesList == null) {
        	summariesList = new List<Map<String, Object>>();
        }
        
        if(String.isNotBlank(gspId) && String.isNotBlank(executionUniqueKey)) {
            Map<String, Object> extraInfo = new Map<String, Object>();
            Map<String, Object> extraInfoByObject = new Map<String, Object>();

            extraInfo.put('executionUniqueKey', executionUniqueKey);

            for(GRAX_Schedule_Process__c gsp : [SELECT Id, Name, type__c, Name__c, Object_Name__c, Start_Time__c, Last_Run_Date__c, Progressive__c, Archive__c, OwnerId, Owner.Name, Send_Notifications__c FROM GRAX_Schedule_Process__c WHERE Id = :gspId AND Execution_Unique_Key__c = :executionUniqueKey LIMIT 1]) {
                extraInfo.put('spId', gsp.Id);
                extraInfo.put('spName', String.isNotBlank(gsp.Name__c) ? gsp.Name__c : GRAXBackupCtrl.getDefaultSpName(gsp));
                extraInfo.put('objectName', gsp.Object_Name__c);
                extraInfo.put('isProgressive', gsp.Progressive__c);
                extraInfo.put('isArchive', gsp.Archive__c);
                extraInfo.put('OwnerId', gsp.OwnerId);
                extraInfo.put('OwnerName', gsp.Owner.Name);
                extraInfo.put('sendNotification', gsp.Send_Notifications__c);

                Map<String, Object> summaryResults = new Map<String, Object>();
                summaryResults.put('startTime', gsp.Start_Time__c);
                summaryResults.put('endTime', gsp.Last_Run_Date__c);
                summaryResults.put('timeElapsed', gsp.Last_Run_Date__c.getTime() - gsp.Start_Time__c.getTime());

                Map<String, Object> summaryMap;
                for(GRAX_Data_Record__c gdr : [SELECT Id, Salesforce_Object__c, Overall_SFObject_Process_Start_Time__c, Overall_SFObject_Process_End_Time__c FROM GRAX_Data_Record__c WHERE GRAX_Schedule_Process__c = :gspId AND Execution_Unique_Key__c = :executionUniqueKey AND Overall_SFObject_Process_Start_Time__c <> null AND Overall_SFObject_Process_End_Time__c <> null]) {
                    summaryMap = new Map<String, Object>();
                    summaryMap.put('startTime', gdr.Overall_SFObject_Process_Start_Time__c);
                    summaryMap.put('endTime', gdr.Overall_SFObject_Process_End_Time__c);
                    summaryMap.put('timeElapsed', gdr.Overall_SFObject_Process_End_Time__c.getTime() - gdr.Overall_SFObject_Process_Start_Time__c.getTime());
                    
                    extraInfoByObject.put(gdr.Salesforce_Object__c, summaryMap);
                }

                extraInfo.put('summaryResults', summaryResults);
                extraInfo.put('summaryMap', extraInfoByObject);
            }
            
            summariesList.add(extraInfo);
        }
    }
    
    public static void sendSummaries() {
        if(summariesList <> null && summariesList.size() > 0) {
            GRAXSettings gxcSettings = new GRAXSettings();

            String url = gxcSettings.graxConfig.GRAX_Flow_URL__c + '/grax-app/grax-data-lake/generateBackupSummaries';
            url += '?orgid=' + UserInfo.getOrganizationId();
            url += '&sessionid=' + UserInfo.getSessionId();
            url += '&userid=' + UserInfo.getUserId();
            url += '&endpoint=' + EncodingUtil.urlencode(GRAXUtils.getExternalAPIEndpoint(), 'utf-8');

            String ns = GRAXUtils.getPureNameSpace();
            if(ns <> null) {
                url += '&ns=' + ns;
            }
            
            // DEBUG ONLY!!!
            // url += '&doInsert=false&_regenerate=true'; // DEBUG ONLY!!!
            // DEBUG ONLY!!!

            System.debug(JSON.serialize(summariesList));
                
            GRAXCloud.CallOutResponse callOutRes = GRAXCloud.calloutnow(url, JSON.serialize(summariesList));
            
            System.debug(callOutRes);

            if(callOutRes.success) {
                summariesList.clear();
            }
        }
    }
    
}