metadata/objects/GRAX_Archive_Process__c.object
<CustomObject>
    <description>This object is used when the user creates a &quot;Scheduled Process&quot; and decides to Archive records from Salesforce.</description>
    <fields>
        <fullName>Async_Records_Successfully_Sent__c</fullName>
        <label># Async Records Successfully Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Async_Records_to_Process__c</fullName>
        <label># Async Records to Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Archive Processes</relationshipLabel>
        <relationshipName>GRAX_Archive_Processes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Records_Successfully_Sent__c</fullName>
        <label># Records Successfully Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_To_Process__c</fullName>
        <description>Count of the # of records which have been processed within Salesforce</description>
        <label># Records To Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Records_To_Process__c &gt; 0 &amp;&amp; Records_Successfully_Sent__c = Records_To_Process__c &amp;&amp; Async_Records_Successfully_Sent__c = Async_Records_to_Process__c &amp;&amp; Total_SFDC_Records_Deleted__c = 0 &amp;&amp; Total_SFDC_Records_Failed_to_Delete__c = 0, 
  &apos;Ready to Delete&apos;,
  IF(Total_SFDC_Records__c &gt; 0 &amp;&amp; Total_SFDC_Records__c != Total_SFDC_Records_Deleted__c + Total_SFDC_Records_Failed_to_Delete__c &amp;&amp; (Total_SFDC_Records_Deleted__c &gt; 0 || Total_SFDC_Records_Failed_to_Delete__c &gt; 0),
    &apos;Delete Process Started&apos;,
    IF(Total_SFDC_Records__c &gt; 0 &amp;&amp; Total_SFDC_Records__c = Total_SFDC_Records_Deleted__c + Total_SFDC_Records_Failed_to_Delete__c,
      &apos;Delete Process Completed&apos;,
      IF(ISPICKVAL(GRAX_Schedule_Process__r.Status__c, &apos;Completed&apos;) &amp;&amp; Records_To_Process__c = 0,
        &apos;Delete Process Completed&apos;,
        &apos;Waiting Backup to Complete&apos;
      )
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>GRAX Archive Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Archive Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Archive Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>This object is related to the GRAX Schedule Process Object. These records contain the object and relationship to the Salesforce record(s) which will be backed up/archived from Salesforce.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Error_Message</description>
        <inlineHelpText>Description of the Error message received</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Archive_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GRAX Archive Process</label>
        <referenceTo>GRAX_Archive_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Sent_Date__c</fullName>
        <description>Last_Sent_Date</description>
        <label>Last Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Records_To_Process__c</fullName>
        <label># Records To Process</label>
        <summaryForeignKey>GRAX_Data_Record_Id__c.GRAX_Data_Record__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>Salesforce_Object</description>
        <inlineHelpText>Name of Salesforce object which is being backed up</inlineHelpText>
        <label>Salesforce Object</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Times_Sent__c</fullName>
        <description>of_Times_Sent</description>
        <label># of Times Sent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAX_Data_Record_Id__c.object
<CustomObject>
    <description>This object contains the specific Salesforce record id which will be backed up/archived as part of the GRAX Scheduled process. These records are automatically deleted at the conclusion of a successful GRAX Scheduled Process.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Data_Record__c</fullName>
        <label>GRAX Data Record</label>
        <referenceTo>GRAX_Data_Record__c</referenceTo>
        <relationshipLabel>GRAX Data Record Ids</relationshipLabel>
        <relationshipName>GRAX_Data_Record_Ids</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To be Deleted</fullName>
                </value>
                <value>
                    <fullName>Deleted with Master Parent</fullName>
                </value>
                <value>
                    <fullName>Successfully Deleted</fullName>
                </value>
                <value>
                    <fullName>Delete Error</fullName>
                </value>
                <value>
                    <fullName>Sent to GRAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Data Record Id</label>
    <nameField>
        <displayFormat>GRAX-RecId-{000000000}</displayFormat>
        <label>GRAX Data Record Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Record Ids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Archive</description>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Field__c</fullName>
        <description>Date_Field</description>
        <inlineHelpText>Salesforce field on the selected object from which the Start &amp; End Dates are being used</inlineHelpText>
        <label>Date Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Run_Date__c</fullName>
        <description>Next_Run_Date</description>
        <inlineHelpText>Next date/time this Scheduled Process will execute</inlineHelpText>
        <label>Next Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object_Name</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progressive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Progressive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <description>Schedule_Type</description>
        <inlineHelpText>Frequency of when the Scheduled Process will run</inlineHelpText>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Once</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select_Criteria__c</fullName>
        <description>Select_Criteria</description>
        <label>Select Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main Object not modified</fullName>
                </value>
                <value>
                    <fullName>Main Object and Children not modified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors sending data</fullName>
                </value>
                <value>
                    <fullName>Sending data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Deleting Salesforce records</fullName>
                </value>
                <value>
                    <fullName>Pending send data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors deleting records</fullName>
                </value>
                <value>
                    <fullName>Starting Archive Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Start_Datetime__c</fullName>
        <inlineHelpText>Date/Time from the field value in the &quot;Date Field&quot; from when this Scheduled Process will begin.</inlineHelpText>
        <label>Target Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXBatchToCleanDataRecordsTest.cls
/*****************************************************************************************
Name              : GRAXBatchToCleanDataRecordsTest
Description       : 
Revision History  :
Created/Modified by   Created/Modified Date     Requested by        Related Task/Issue     
----------------------------------------------------------------------------------------
1. Leandro Brunner       	04/17/2018			David Mackey        https://app.asana.com/0/326600806074978/633149554508924/f
2. Ariel Yankelevich     	05/07/2019          David Mackey        Remove Reference to GRAX Query Object (https://app.asana.com/0/326600806074978/1121760476564626/f)
******************************************************************************************/
@isTest
private class GRAXBatchToCleanDataRecordsTest {
    @TestSetup
    static void setup() {
        // To delete
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'CreatedDate';
        gsp.Target_Start_Datetime__c = Datetime.now().addDays(-3);
        gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = true;
        gsp.Progressive__c = true;
		gsp.Execution_Unique_Key__c = 'testing123';
        insert gsp;

        GRAX_Archive_Process__c archiveProc = new GRAX_Archive_Process__c();
        archiveProc.GRAX_Schedule_Process__c = gsp.Id;
        archiveProc.Async_Records_Successfully_Sent__c = 0;
        archiveProc.Async_Records_to_Process__c = 0;
        archiveProc.Records_Successfully_Sent__c = 2;
        archiveProc.Records_To_Process__c = 0;
        insert archiveProc;

        // To delete
        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.Salesforce_Object__c = 'GRAX_Schedule_Process__c';
        dr.Status__c = 'Sent Successful';
        dr.of_Times_Sent__c = 1;
        dr.Error_Message__c = null;
        //dr.GRAX_Archive_Process__c = archiveProc.Id;
        dr.Last_Sent_Date__c = Date.today().addDays(-3);
        dr.Execution_Unique_Key__c = 'testing123';

        // To delete
        GRAX_Data_Record__c dr2 = new GRAX_Data_Record__c();
        dr2.Salesforce_Object__c = 'GRAX_Schedule_Process__c';
        dr2.Status__c = 'Sent Successful';
        dr2.of_Times_Sent__c = 1;
        dr2.Error_Message__c = null;
        dr2.GRAX_Archive_Process__c = archiveProc.Id;
        dr2.Last_Sent_Date__c = Date.today().addDays(-2);
		dr2.Execution_Unique_Key__c = 'testing123';

        GRAX_Data_Record__c dr3 = new GRAX_Data_Record__c();
        dr3.Salesforce_Object__c = 'GRAX_Schedule_Process__c';
        dr3.Status__c = 'Processing';
        dr3.of_Times_Sent__c = 1;
        dr3.Error_Message__c = null;
        dr3.GRAX_Schedule_Process__c = gsp.Id;
        dr3.GRAX_Archive_Process__c = archiveProc.Id;
        dr3.Last_Sent_Date__c = Date.today();
		dr3.Execution_Unique_Key__c = 'testing123';

		insert new List<GRAX_Data_Record__c> { dr, dr2, dr3 };

        // To delete
        GRAX_Data_Record_Id__c dri = new GRAX_Data_Record_Id__c();
        dri.GRAX_Data_Record__c = dr.Id;
		dri.Execution_Unique_Key__c = 'testing123';

        // To delete
        GRAX_Data_Record_Id__c dri2 = new GRAX_Data_Record_Id__c();
        dri2.GRAX_Data_Record__c = dr2.Id;
		dri2.Execution_Unique_Key__c = 'testing123';

        GRAX_Data_Record_Id__c dri3 = new GRAX_Data_Record_Id__c();
        dri3.GRAX_Data_Record__c = dr3.Id;
		dri3.Execution_Unique_Key__c = 'testing123';

		insert new List<GRAX_Data_Record_Id__c> { dri, dri2, dri3 };
    }

    @isTest(seeAllData = false)
    static void GRAXBatchToCleanDataRecordsTest1() {
    	delete [SELECT Id FROM GRAX_Data_Record_Id__c];
        
        Integer objectIndex = GRAXBatchToCleanDataRecords.objects2Execute.indexOf('GRAX_Data_Record__c');

        Test.startTest();
        database.executebatch(new GRAXBatchToCleanDataRecords(objectIndex, null, null), 10);
        Test.stopTest();
        
        System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record__c].size());
    }

    @isTest(seeAllData = false)
    static void GRAXBatchToCleanDataRecordsTest2() {
        Integer objectIndex = GRAXBatchToCleanDataRecords.objects2Execute.indexOf('GRAX_Data_Record_Id__c');

        Test.startTest();
        database.executebatch(new GRAXBatchToCleanDataRecords(objectIndex, null, null), 10);
        Test.stopTest();

        System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record_Id__c].size());
    }

    @isTest(seeAllData = false)
    static void GRAXBatchToCleanDataRecordsTest3() {
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'CreatedDate';
        gsp.Target_Start_Datetime__c = Datetime.now().addDays(-3);
        gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = true;
        gsp.Progressive__c = false;
        insert gsp;

        GRAX_Archive_Process__c archiveProc = new GRAX_Archive_Process__c();
        archiveProc.GRAX_Schedule_Process__c = gsp.Id;
        archiveProc.Async_Records_Successfully_Sent__c = 0;
        archiveProc.Async_Records_to_Process__c = 0;
        archiveProc.Records_Successfully_Sent__c = 1;
        archiveProc.Records_To_Process__c = 0;
        insert archiveProc;

        Integer objectIndex = GRAXBatchToCleanDataRecords.objects2Execute.indexOf('GRAX_Archive_Process__c');

        Test.startTest();
        database.executebatch(new GRAXBatchToCleanDataRecords(objectIndex, null, null), 10);
        Test.stopTest();

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE GRAX_Schedule_Process__c =: gsp.Id].size());
    }

    @isTest(seeAllData = false)
    static void GRAXBatchToCleanDataRecordsTest4() {
        delete [SELECT Id FROM GRAX_Data_Record_Id__c];
        
        Integer objectIndex = GRAXBatchToCleanDataRecords.objects2Execute.indexOf('GRAX_Data_Record__c');
		
		List<GRAX_Schedule_Process__c> gsp = [SELECT Id, Execution_Unique_Key__c FROM GRAX_Schedule_Process__c WHERE Object_Name__c = 'GRAX_Schedule_Process__c' LIMIT 1];
		
        Test.startTest();
        database.executebatch(new GRAXBatchToCleanDataRecords(objectIndex, gsp[0].Id, gsp[0].Execution_Unique_Key__c), 10);
        Test.stopTest();

        System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record__c].size());
    }

    @isTest(seeAllData = false)
    static void GRAXBatchToCleanDataRecordsTest5() {
        Integer objectIndex = GRAXBatchToCleanDataRecords.objects2Execute.indexOf('GRAX_Data_Record_Id__c');

		List<GRAX_Schedule_Process__c> gsp = [SELECT Id, Execution_Unique_Key__c FROM GRAX_Schedule_Process__c WHERE Object_Name__c = 'GRAX_Schedule_Process__c' LIMIT 1];

		Test.startTest();
        database.executebatch(new GRAXBatchToCleanDataRecords(objectIndex, gsp[0].Id, gsp[0].Execution_Unique_Key__c), 10);
        Test.stopTest();

		System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record_Id__c].size());
    }
}