metadata/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>This object is related to the GRAX Schedule Process Object. These records contain the object and relationship to the Salesforce record(s) which will be backed up/archived from Salesforce.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>Salesforce_Object</description>
        <inlineHelpText>Name of Salesforce object which is being backed up</inlineHelpText>
        <label>Salesforce Object</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAX_Data_Record_Id__c.object
<CustomObject>
    <description>This object contains the specific Salesforce record id which will be backed up/archived as part of the GRAX Scheduled process. These records are automatically deleted at the conclusion of a successful GRAX Scheduled Process.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Data_Record__c</fullName>
        <label>GRAX Data Record</label>
        <referenceTo>GRAX_Data_Record__c</referenceTo>
        <relationshipLabel>GRAX Data Record Ids</relationshipLabel>
        <relationshipName>GRAX_Data_Record_Ids</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SFDC_Id__c</fullName>
        <description>SFDC_Id</description>
        <label>SFDC Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To be Deleted</fullName>
                </value>
                <value>
                    <fullName>Deleted with Master Parent</fullName>
                </value>
                <value>
                    <fullName>Successfully Deleted</fullName>
                </value>
                <value>
                    <fullName>Delete Error</fullName>
                </value>
                <value>
                    <fullName>Sent to GRAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Data Record Id</label>
    <nameField>
        <displayFormat>GRAX-RecId-{000000000}</displayFormat>
        <label>GRAX Data Record Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Record Ids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Archive</description>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Field__c</fullName>
        <description>Date_Field</description>
        <inlineHelpText>Salesforce field on the selected object from which the Start &amp; End Dates are being used</inlineHelpText>
        <label>Date Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Run_Date__c</fullName>
        <description>Last_Run_Date</description>
        <inlineHelpText>Last time this Scheduled Process was run</inlineHelpText>
        <label>Last Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Next_Run_Date__c</fullName>
        <description>Next_Run_Date</description>
        <inlineHelpText>Next date/time this Scheduled Process will execute</inlineHelpText>
        <label>Next Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object_Name</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <description>Schedule_Type</description>
        <inlineHelpText>Frequency of when the Scheduled Process will run</inlineHelpText>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Once</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select_Criteria__c</fullName>
        <description>Select_Criteria</description>
        <label>Select Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main Object not modified</fullName>
                </value>
                <value>
                    <fullName>Main Object and Children not modified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors sending data</fullName>
                </value>
                <value>
                    <fullName>Sending data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Deleting Salesforce records</fullName>
                </value>
                <value>
                    <fullName>Pending send data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors deleting records</fullName>
                </value>
                <value>
                    <fullName>Starting Archive Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_End_Datetime__c</fullName>
        <inlineHelpText>Date/Time from the field value in the &quot;Date Field&quot; from when this Scheduled Process will end.</inlineHelpText>
        <label>Target End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Target_Start_Datetime__c</fullName>
        <inlineHelpText>Date/Time from the field value in the &quot;Date Field&quot; from when this Scheduled Process will begin.</inlineHelpText>
        <label>Target Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Records_Sent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Records Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_To_Send__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Records To Send</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hierarchy</fullName>
                    <default>true</default>
                    <label>Hierarchy</label>
                </value>
                <value>
                    <fullName>Multi-Object</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAXQuery__c.object
<CustomObject>
    <description>This object is used to store the custom fields and filters used by GRAX Connect</description>
    <label>GRAX : Object Configuration</label>
    <nameField>
        <displayFormat>GRAX-{000000}</displayFormat>
        <label>GRAXQueries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX : Object Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXBatchToProcessSchedJobTest.cls
/*****************************************************************************************
Name              : GRAXBatchToProcessSchedJobTest
Description       : 
Revision History  :
Created/Modified by   Created/Modified Date     Requested by        Related Task/Issue     
----------------------------------------------------------------------------------------
1. Leandro Brunner    		05/23/2018          David Mackey        "Restore" Button for Backup/Archive (https://app.asana.com/0/326600806074978/665432711419635/f)
2. Ariel Yankelevich     	05/07/2019          David Mackey        Remove Reference to GRAX Query Object (https://app.asana.com/0/326600806074978/1121760476564626/f)
******************************************************************************************/
@IsTest(SeeAllData=false)
public class GRAXBatchToProcessSchedJobTest {

    @isTest
    static void GRAXBatchToProcessSchedJobTest1() {
        GRAX_Schedule_Process__c gq = new GRAX_Schedule_Process__c();
        gq.Object_Name__c = 'GRAX_Schedule_Process__c';
        insert gq;

        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(1);
        //gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        gsp.type__c = 'Multi-Object';
        gsp.Execution_Unique_Key__c = 'testing123';
        insert gsp;

        GRAXUtils.setSelectionJSON(gsp.Id, '[{"uniqueKey":"' + GRAXUtils.getNameSpacePrefix() + 'GRAX_Schedule_Process__c","parentUniqueKey":null,"relatedFieldName":null,"name":"' + GRAXUtils.getNameSpacePrefix() + 'GRAX_Schedule_Process__c","childObjRelStructure":[]}]');

        System.assertNotEquals(null, GRAXUtils.getSelectionJSON(gsp.Id));

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, 'OK', '{"message": "Test successful"}', null);

        GRAXBatchToProcessSchedJob b = new GRAXBatchToProcessSchedJob(gsp.Id, null, 0, null, true, true);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Id jobId = Database.executebatch(new GRAXBatchToProcessSchedJobMainObject(b), 1);

        Test.stopTest();

        for(GRAX_Schedule_Process__c schedProcess : [SELECT Id, Next_Run_Date__c, Last_Run_Date__c, Status__c FROM GRAX_Schedule_Process__c WHERE Id = :gsp.Id]) {
            System.assertEquals('Completed', schedProcess.Status__c);
        }

        //GRAX_Data_Record__c dr = [SELECT Id FROM GRAX_Data_Record__c WHERE GRAX_Schedule_Process__c = :gsp.Id LIMIT 1];

        //System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record_Id__c WHERE GRAX_Data_Record__c = :dr.Id AND SFDC_Id__c = :gq.Id].size());
    }

    @isTest
    static void GRAXBatchToProcessSchedJobTest2() {
        GRAX_Data_Record__c gq = new GRAX_Data_Record__c();
        gq.Salesforce_Object__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Data_Record__c';
        insert gq;

        Attachment att = new Attachment();      
        att.Name = 'Test';
        att.body = Blob.valueOf('Test');
        att.parentId = gq.id;
        insert att;

        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Data_Record__c';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_End_Datetime__c = Date.today().addDays(1);
        //gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        insert gsp;

        GRAXUtils.setSelectionJSON(gsp.Id, '{"uniqueKey":"' + GRAXUtils.getNameSpacePrefix() + 'GRAX_Data_Record__c","parentUniqueKey":null,"relatedFieldName":null,"name":"' + GRAXUtils.getNameSpacePrefix() + 'GRAX_Data_Record__c","childObjRelStructure":[{"uniqueKey":"GRAX_Data_Record__c_Attachments","parentUniqueKey":"' + GRAXUtils.getNameSpacePrefix() + 'GRAX_Data_Record__c","relatedFieldName":"ParentId","name":"Attachment","childObjRelStructure":[]}]}');

        String selectedJSON = GRAXUtils.getSelectionJSON(gsp.Id);

        System.assertNotEquals(null, selectedJSON);

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, 'OK', '{"message": "Test successful"}', null);
        
        GRAXBatchToProcessSchedJob b1 = new GRAXBatchToProcessSchedJob(gsp.Id, null, 0, null, false, false);
        GRAXBatchToProcessSchedJob b2 = new GRAXBatchToProcessSchedJob(gsp.Id, b1.objects2Process, 1, b1.currentSelectCriteria, b1.isExecuteNow, false);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Database.executebatch(b1, 1);
        //Database.executebatch(b2, 1);

        Test.stopTest();

        GRAX_Data_Record__c dr;

        for(GRAX_Data_Record__c r : [SELECT Id FROM GRAX_Data_Record__c WHERE GRAX_Schedule_Process__c = :gsp.Id LIMIT 1]) {
            dr = r;
        }

        System.assertNotEquals(null, dr);

        System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record_Id__c WHERE GRAX_Data_Record__c = :dr.Id AND SFDC_Id__c = :gq.Id].size());
    }

    @isTest
    static void GRAXBatchToProcessSchedJobTestAttachmentArchive() {
        GRAX_Data_Record__c gq = new GRAX_Data_Record__c();
        gq.Salesforce_Object__c = 'GRAX_Data_Record__c';
        insert gq;

        Attachment att = new Attachment();      
        att.Name = 'Test';
        att.body = Blob.valueOf('Test');
        att.parentId = gq.id;
        insert att;

        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'GRAX_Data_Record__c';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(-1);
        //gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = true;
        insert gsp;

        GRAXUtils.setSelectionJSON(gsp.Id, '{"uniqueKey":"GRAX_Data_Record__c_Attachments","parentUniqueKey":"GRAX_Data_Record__c","relatedFieldName":"ParentId","name":"Attachment","childObjRelStructure":[]}');

        System.assertNotEquals(null, GRAXUtils.getSelectionJSON(gsp.Id));

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, 'OK', '{"message": "Test successful"}', null);

        GRAXBatchToProcessSchedJob b = new GRAXBatchToProcessSchedJob(gsp.Id, null, 0, null, false, false);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Id jobId = Database.executebatch(b, 2);

        Test.stopTest();

        GRAX_Data_Record__c dr = [SELECT Id FROM GRAX_Data_Record__c WHERE GRAX_Schedule_Process__c = :gsp.Id LIMIT 1];

        Attachment att2 = [SELECT Id, Body FROM Attachment WHERE ParentId = :dr.Id ORDER BY CreatedDate DESC LIMIT 1];
        String att2BodyString = att2.Body.toString();

        System.assertNotEquals(null, att2);

        System.assert(att2BodyString.contains('GRAX_Data_Record_Id'));
        System.assert(att2BodyString.contains('Ready to Process'));
    }
    
    @isTest(seeAllData = false)
    static void GRAXBatchToProcessSchedJobTestContentDocument() {
        GRAX_Schedule_Process__c gq = new GRAX_Schedule_Process__c();
        gq.Object_Name__c = 'GRAX_Schedule_Process__c';
        insert gq;

        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.VersionData = Blob.valueOf('some content to access later on');
        cv.Title = 'some title';
        cv.PathOnClient = 'some title'+'.txt';        
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink();
		cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
		cdl.LinkedEntityId = gq.id;
		cdl.ShareType = 'V';
		insert cdl;
              
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(-1);
        //gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        insert gsp;

        GRAXUtils.setSelectionJSON(gsp.Id, '{"uniqueKey":"GRAX_Schedule_Process__c_ContentDocumentLink","parentUniqueKey":"GRAX_Schedule_Process__c","relatedFieldName":"LinkedEntityId","name":"ContentDocumentLink","childObjRelStructure":[]}');

        System.assertNotEquals(null, GRAXUtils.getSelectionJSON(gsp.Id));

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, 'OK', '{"message": "Test successful"}', null);

        GRAXBatchToProcessSchedJob b = new GRAXBatchToProcessSchedJob(gsp.Id, null, 0, null, false, false);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Id jobId = Database.executebatch(b, 2);

        Test.stopTest();
	
		System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record__c WHERE GRAX_Schedule_Process__c = :gsp.Id AND Salesforce_Object__c IN ('ContentDocumentLink', 'ContentVersion')].size());
    }
    
    @isTest(seeAllData = false OnInstall=false)
    static void GRAXBatchToProcessSchedJobTestFeedComment() {
        Account acc = new Account(Name = 'Test acc1', BillingCity = 'USA');
        insert acc;

        FeedItem fi = new FeedItem();
        fi.ParentId = acc.Id;
        fi.Body = 'test body';
        insert fi;
        
        FeedComment fc = new FeedComment();
        fc.FeedItemId = fi.Id;
        fc.CommentBody = 'test body';
        insert fc;
              
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'Account';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(-1);
        //gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        insert gsp;

        GRAXUtils.setSelectionJSON(gsp.Id, '{"uniqueKey":"Account_FeedComment","parentUniqueKey":"Account","relatedFieldName":"ParentId","name":"FeedComment","childObjRelStructure":[]}');
        
        System.assertNotEquals(null, GRAXUtils.getSelectionJSON(gsp.Id));

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, 'OK', '{"message": "Test successful"}', null);

        GRAXBatchToProcessSchedJob b = new GRAXBatchToProcessSchedJob(gsp.Id, null, 0, null, false, false);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Id jobId = Database.executebatch(b, 2);

        Test.stopTest();
	
		System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record__c WHERE GRAX_Schedule_Process__c = :gsp.Id AND Salesforce_Object__c IN ('FeedComment')].size());
    }

    @isTest
    static void GRAXBatchToProcessSchedJobExecuteNowTest() {
        Datetime now = Datetime.now();
        
        GRAX_Data_Record__c gq = new GRAX_Data_Record__c();
        gq.Salesforce_Object__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Data_Record__c';
        insert gq;

        Attachment att = new Attachment();      
        att.Name = 'Test';
        att.body = Blob.valueOf('Test');
        att.parentId = gq.id;
        insert att;

        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'CreatedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(-1);
        gsp.Target_End_Datetime__c = Date.today().addDays(1);
        //gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = now;
        gsp.Archive__c = true;
        insert gsp;

        GRAXUtils.setSelectionJSON(gsp.Id, '{"uniqueKey":"' + GRAXUtils.getNameSpacePrefix() + 'GRAX_Data_Record__c","parentUniqueKey":null,"relatedFieldName":null,"name":"' + GRAXUtils.getNameSpacePrefix() + 'GRAX_Data_Record__c","childObjRelStructure":[]}');

        System.assertNotEquals(null, GRAXUtils.getSelectionJSON(gsp.Id));

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, 'OK', '{"message": "Test successful"}', null);

        GRAXBatchToProcessSchedJob b = new GRAXBatchToProcessSchedJob(gsp.Id, null, 0, null, true, false);

        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Id jobId = Database.executebatch(b, 1);

        Test.stopTest();

        GRAX_Data_Record__c dr = [SELECT Id FROM GRAX_Data_Record__c WHERE GRAX_Schedule_Process__c = :gsp.Id LIMIT 1];

        //System.assertEquals(1, [SELECT Id FROM GRAX_Schedule_Process__c WHERE Id = :gsp.Id AND Next_Run_Date__c = :now].size());
        //System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record_Id__c WHERE Status__c = 'Successfully Deleted' AND GRAX_Data_Record__c = :dr.Id AND SFDC_Id__c = :gq.Id].size());
        //System.assertEquals(0, [SELECT Id FROM GRAXQuery__c WHERE Id = :gq.Id].size());
    }

    @isTest
    static void GRAXBatchToProcessSchedJobTestStatus() {
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Total_Records_To_Send__c = 10;
        gsp.Total_Records_Sent__c = 10;
        insert gsp;

        gsp.Status__c = 'Completed';
        update gsp;

        for(GRAX_Schedule_Process__c gsp2 : [SELECT Status__c FROM GRAX_Schedule_Process__c WHERE Id = :gsp.Id]) {
            System.assertEquals(gsp2.Status__c, gsp.Status__c);
            System.assertEquals(gsp2.Status__c, 'Completed');
        }
    }
    
}