metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXRESTWS_BackupProcessNotificationTest.cls
/*****************************************************************************************
Name              : GRAXRESTWS_BackupProcessNotification
Description       : Test methods for the GRAXRESTWS_RestoreProcessNotification APEX Class
Revision History  :
Created/Modified by   Created/Modified Date     Requested by          Related Task/Issue             
----------------------------------------------------------------------------------------
1. Leandro Brunner	  05/29/2019			    David Mackey          Review "Backup Stats" (https://app.asana.com/0/326600806074978/1107778902588819/f)
******************************************************************************************/
@isTest
public class GRAXRESTWS_BackupProcessNotificationTest {
	
    @isTest
    static void GRAXRESTWS_BackupProcessNotification_Test() {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

		GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
		gsp.Execution_Unique_Key__c = 'test';
		gsp.Name__c = 'test';
		insert gsp;

		GRAXUtils.setSelectionJSON(gsp.Id, '["' + gsp.Id + '"]', 'usersSelectionJSON.txt');
		GRAXUtils.setSelectionJSON(gsp.Id, 'test@test.com,test2@test.com', 'extraEmails.txt');
        
        String jsonString = '{"GRAX_Schedule_Process" : "' + gsp.Id + '", "GRAX_Execution_Unique_Key" : "' + gsp.Execution_Unique_Key__c + '", "GRAX_Backup_Summary" : "test", "GRAX_Backup_Summary_Link": "http://test.com", "GRAX_Backup_Summary_Name": "test" }';

        req.requestUri = '/services/apexrest/GRAXRESTWS/BackupProcessNotification/';
        req.requestBody = Blob.valueOf(jsonString);                   
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response = res;
        
        GRAXRESTWS_BackupProcessNotification.doPost();
        
        String result = String.valueOf(res.responseBody);
    }
}