metadata/objects/GRAXSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>GRAX by Harding Point Settings. https://grax.io</description>
    <fields>
        <fullName>Graph_DB_Password__c</fullName>
        <defaultValue>&quot;b.o70mLuaAUEUO.BA1vM10dsFOjtEKm&quot;</defaultValue>
        <label>Graph DB Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graph_DB_URL__c</fullName>
        <defaultValue>&quot;https://db-ljovrmxu24s76s1jbphc.graphenedb.com:24780&quot;</defaultValue>
        <inlineHelpText>E.G. https://hobby-ilpalckeehocgbkeoncdnjal.dbs.graphenedb.com:24780</inlineHelpText>
        <label>Graph DB URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graph_DB_Username__c</fullName>
        <defaultValue>&quot;app81968631-13521279694483497&quot;</defaultValue>
        <inlineHelpText>Graph DB Username</inlineHelpText>
        <label>Graph DB Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>GRAX Settings</label>
</CustomObject>

metadata/classes/Neo4jClient.cls
public with sharing class Neo4jClient {

    private HttpRequest request;

    public Neo4jClient() {

        GRAXSettings__c settings = GRAXSettings__c.getOrgDefaults();

        String basicAuthentication = settings.Graph_DB_Username__c + ':' + settings.Graph_DB_Password__c;
        basicAuthentication = EncodingUtil.base64Encode(Blob.valueOf(basicAuthentication));

        request = new HttpRequest();
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Accept', 'application/json');
        request.setHeader('Authorization', 'Basic ' + basicAuthentication);
        request.setEndpoint(settings.Graph_DB_URL__c + '/db/data/cypher');
    }

    public HttpResponse query(String data) {

        request.setBody(data);
        return send();
    }

    private HttpResponse send() {

        System.debug(request.getBody());
        return (new Http()).send(request);
    }

}