metadata/objects/GRAX_Archive_Process__c.object
<CustomObject>
    <description>This object is used when the user creates a &quot;Scheduled Process&quot; and decides to Archive records from Salesforce.</description>
    <fields>
        <fullName>Async_Records_Successfully_Sent__c</fullName>
        <label># Async Records Successfully Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Async_Records_to_Process__c</fullName>
        <label># Async Records to Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Archive Processes</relationshipLabel>
        <relationshipName>GRAX_Archive_Processes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Records_Successfully_Sent__c</fullName>
        <label># Records Successfully Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_To_Process__c</fullName>
        <description>Count of the # of records which have been processed within Salesforce</description>
        <label># Records To Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Records_To_Process__c &gt; 0 &amp;&amp; Records_Successfully_Sent__c = Records_To_Process__c &amp;&amp; Async_Records_Successfully_Sent__c = Async_Records_to_Process__c &amp;&amp; Total_SFDC_Records_Deleted__c = 0 &amp;&amp; Total_SFDC_Records_Failed_to_Delete__c = 0, 
  &apos;Ready to Delete&apos;,
  IF(Total_SFDC_Records__c &gt; 0 &amp;&amp; Total_SFDC_Records__c != Total_SFDC_Records_Deleted__c + Total_SFDC_Records_Failed_to_Delete__c &amp;&amp; (Total_SFDC_Records_Deleted__c &gt; 0 || Total_SFDC_Records_Failed_to_Delete__c &gt; 0),
    &apos;Delete Process Started&apos;,
    IF(Total_SFDC_Records__c &gt; 0 &amp;&amp; Total_SFDC_Records__c = Total_SFDC_Records_Deleted__c + Total_SFDC_Records_Failed_to_Delete__c,
      &apos;Delete Process Completed&apos;,
      IF(ISPICKVAL(GRAX_Schedule_Process__r.Status__c, &apos;Completed&apos;) &amp;&amp; Records_To_Process__c = 0,
        &apos;Delete Process Completed&apos;,
        &apos;Waiting Backup to Complete&apos;
      )
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>GRAX Archive Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Archive Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Archive Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>This object is related to the GRAX Schedule Process Object. These records contain the object and relationship to the Salesforce record(s) which will be backed up/archived from Salesforce.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Archive_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GRAX Archive Process</label>
        <referenceTo>GRAX_Archive_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Records_To_Process__c</fullName>
        <label># Records To Process</label>
        <summaryForeignKey>GRAX_Data_Record_Id__c.GRAX_Data_Record__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>Salesforce_Object</description>
        <inlineHelpText>Name of Salesforce object which is being backed up</inlineHelpText>
        <label>Salesforce Object</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Times_Sent__c</fullName>
        <description>of_Times_Sent</description>
        <label># of Times Sent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAX_Data_Record_Id__c.object
<CustomObject>
    <description>This object contains the specific Salesforce record id which will be backed up/archived as part of the GRAX Scheduled process. These records are automatically deleted at the conclusion of a successful GRAX Scheduled Process.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Data_Record__c</fullName>
        <label>GRAX Data Record</label>
        <referenceTo>GRAX_Data_Record__c</referenceTo>
        <relationshipLabel>GRAX Data Record Ids</relationshipLabel>
        <relationshipName>GRAX_Data_Record_Ids</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To be Deleted</fullName>
                </value>
                <value>
                    <fullName>Deleted with Master Parent</fullName>
                </value>
                <value>
                    <fullName>Successfully Deleted</fullName>
                </value>
                <value>
                    <fullName>Delete Error</fullName>
                </value>
                <value>
                    <fullName>Sent to GRAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Data Record Id</label>
    <nameField>
        <displayFormat>GRAX-RecId-{000000000}</displayFormat>
        <label>GRAX Data Record Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Record Ids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Archive</description>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Field__c</fullName>
        <description>Date_Field</description>
        <inlineHelpText>Salesforce field on the selected object from which the Start &amp; End Dates are being used</inlineHelpText>
        <label>Date Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Run_Date__c</fullName>
        <description>Next_Run_Date</description>
        <inlineHelpText>Next date/time this Scheduled Process will execute</inlineHelpText>
        <label>Next Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object_Name</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <description>Schedule_Type</description>
        <inlineHelpText>Frequency of when the Scheduled Process will run</inlineHelpText>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Once</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select_Criteria__c</fullName>
        <description>Select_Criteria</description>
        <label>Select Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main Object not modified</fullName>
                </value>
                <value>
                    <fullName>Main Object and Children not modified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors sending data</fullName>
                </value>
                <value>
                    <fullName>Sending data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Deleting Salesforce records</fullName>
                </value>
                <value>
                    <fullName>Pending send data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors deleting records</fullName>
                </value>
                <value>
                    <fullName>Starting Archive Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Start_Datetime__c</fullName>
        <inlineHelpText>Date/Time from the field value in the &quot;Date Field&quot; from when this Scheduled Process will begin.</inlineHelpText>
        <label>Target Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Records_Errors__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Records Errors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Sent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Records Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_To_Send__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Records To Send</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXDataRecordTriggerTest.cls
/*****************************************************************************************
Name              : GRAXDataRecordTriggerTest
Description       : 
Revision History  :
Created/Modified by   Created/Modified Date     Requested by        Related Task/Issue     
----------------------------------------------------------------------------------------
1. Leandro Brunner    06/07/2018
******************************************************************************************/
@isTest
public with sharing class GRAXDataRecordTriggerTest {
    
    @isTest
    public static void rollUpTotalRecordsToProcessTest() {
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'Account';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Datetime.now().addDays(1);
        gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        insert gsp;

        GRAX_Archive_Process__c ap = new GRAX_Archive_Process__c(
            Async_Records_Successfully_Sent__c = 0,
            Async_Records_to_Process__c=0,
            Records_Successfully_Sent__c=0,
            Records_To_Process__c=0,
            GRAX_Schedule_Process__c=gsp.Id
        );
        insert ap;

        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.Status__c = 'Not Sent';
        dr.of_Times_Sent__c = 0;
        dr.GRAX_Archive_Process__c = ap.Id;
        insert dr;

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Records_To_Process__c = 1].size());

        delete dr;

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Records_To_Process__c = 0].size());

        undelete dr;

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Records_To_Process__c = 1].size());
    }

    @isTest
    public static void rollUpTotalRecordsSuccessfullySentTest() {
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'Account';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Datetime.now().addDays(1);
        gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        insert gsp;

        GRAX_Archive_Process__c ap = new GRAX_Archive_Process__c(
            Async_Records_Successfully_Sent__c = 0,
            Async_Records_to_Process__c=0,
            Records_Successfully_Sent__c=0,
            Records_To_Process__c=0,
            GRAX_Schedule_Process__c=gsp.Id
        );
        insert ap;

        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.Status__c = 'Not Sent';
        dr.GRAX_Archive_Process__c = ap.Id;
        insert dr;

        dr.Status__c = 'Sent Successful';
        update dr;

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Records_Successfully_Sent__c = 1].size());

        dr.Status__c = 'Error';
        update dr;

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Records_Successfully_Sent__c = 0].size());
    }

    @isTest
    public static void rollUpTotalAsyncRecordsToProcessTest() {
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'Attachment';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Datetime.now().addDays(1);
        gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = true;
        insert gsp;

        GRAX_Archive_Process__c ap = new GRAX_Archive_Process__c(
            Async_Records_Successfully_Sent__c=0,
            Async_Records_to_Process__c=0,
            Records_Successfully_Sent__c=0,
            Records_To_Process__c=0,
            GRAX_Schedule_Process__c=gsp.Id
        );
        insert ap;

        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.Status__c = 'Not Sent';
        dr.of_Times_Sent__c = 0;
        dr.GRAX_Archive_Process__c = ap.Id;
        dr.Salesforce_Object__c = 'Attachment';
        insert dr;

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Async_Records_to_Process__c = 1].size());

        delete dr;

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Async_Records_to_Process__c = 0].size());

        undelete dr;

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Async_Records_to_Process__c = 1].size());
    }

    @isTest
    public static void rollUpTotalAsyncRecordsSuccessfullySentTest() {
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'Attachment';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Datetime.now().addDays(1);
        gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = true;
        insert gsp;

        GRAX_Archive_Process__c ap = new GRAX_Archive_Process__c(
            Async_Records_Successfully_Sent__c = 0,
            Async_Records_to_Process__c=0,
            Records_Successfully_Sent__c=0,
            Records_To_Process__c=0,
            GRAX_Schedule_Process__c=gsp.Id
        );
        insert ap;

        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.Status__c = 'Not Sent';
        dr.of_Times_Sent__c = 0;
        dr.GRAX_Archive_Process__c = ap.Id;
        dr.Salesforce_Object__c = 'Attachment';
        insert dr;

        GRAX_Data_Record_Id__c dri = new GRAX_Data_Record_Id__c();
        dri.GRAX_Data_Record__c = dr.Id;
        insert dri;

        dri.Status__c = 'Sent to GRAX';
        update dri;
        

        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Async_Records_Successfully_Sent__c = 1].size());
    }
    
    @isTest
    public static void rollUpTotalValuesToScheduleProcessTest() {
    	GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'Account';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Datetime.now().addDays(1);
        gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        gsp.Execution_Unique_Key__c = 'testUniqueKey';
        insert new List<GRAX_Schedule_Process__c>{gsp};
        
        GRAX_Data_Record__c dr1 = new GRAX_Data_Record__c(GRAX_Schedule_Process__c = gsp.Id, Salesforce_Object__c = 'Test', Status__c = 'Processing', Execution_Unique_Key__c = gsp.Execution_Unique_Key__c, of_Times_Sent__c = 0);
        GRAX_Data_Record__c dr2 = new GRAX_Data_Record__c(GRAX_Schedule_Process__c = gsp.Id, Salesforce_Object__c = 'Test', Status__c = 'Processing', Execution_Unique_Key__c = gsp.Execution_Unique_Key__c, of_Times_Sent__c = 0);
        insert new List<GRAX_Data_Record__c>{dr1, dr2};
        
        GRAX_Data_Record_Id__c dri1 = new GRAX_Data_Record_Id__c(GRAX_Data_Record__c = dr1.Id);
        GRAX_Data_Record_Id__c dri2 = new GRAX_Data_Record_Id__c(GRAX_Data_Record__c = dr1.Id);
        GRAX_Data_Record_Id__c dri3 = new GRAX_Data_Record_Id__c(GRAX_Data_Record__c = dr2.Id);
        insert new List<GRAX_Data_Record_Id__c>{dri1, dri2, dri3};
        
        Map<Id, GRAX_Schedule_Process__c> gsp2Check = new Map<Id, GRAX_Schedule_Process__c>([SELECT Id, Total_Records_To_Send__c, Total_Records_Sent__c, Total_Records_Errors__c FROM GRAX_Schedule_Process__c WHERE Id IN :new List<GRAX_Schedule_Process__c>{gsp}]);
		System.assertEquals(3, gsp2Check.get(gsp.Id).Total_Records_To_Send__c);
		System.assertEquals(0, gsp2Check.get(gsp.Id).Total_Records_Sent__c);
		System.assertEquals(0, gsp2Check.get(gsp.Id).Total_Records_Errors__c);
		
		dr1.Status__c = 'Error';
		dr1.of_Times_Sent__c = 5;
		dr2.Status__c = 'Sent Successful';
		update new List<GRAX_Data_Record__c>{dr1, dr2};
		
		gsp2Check = new Map<Id, GRAX_Schedule_Process__c>([SELECT Id, Total_Records_To_Send__c, Total_Records_Sent__c, Total_Records_Errors__c FROM GRAX_Schedule_Process__c WHERE Id IN :new List<GRAX_Schedule_Process__c>{gsp}]);
		System.assertEquals(3, gsp2Check.get(gsp.Id).Total_Records_To_Send__c);
		System.assertEquals(1, gsp2Check.get(gsp.Id).Total_Records_Sent__c);
		System.assertEquals(2, gsp2Check.get(gsp.Id).Total_Records_Errors__c);
    }
}