metadata/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>This object is related to the GRAX Schedule Process Object. These records contain the object and relationship to the Salesforce record(s) which will be backed up/archived from Salesforce.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Error_Message</description>
        <inlineHelpText>Description of the Error message received</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>Salesforce_Object</description>
        <inlineHelpText>Name of Salesforce object which is being backed up</inlineHelpText>
        <label>Salesforce Object</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Times_Sent__c</fullName>
        <description>of_Times_Sent</description>
        <label># of Times Sent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAX_Data_Record_Id__c.object
<CustomObject>
    <description>This object contains the specific Salesforce record id which will be backed up/archived as part of the GRAX Scheduled process. These records are automatically deleted at the conclusion of a successful GRAX Scheduled Process.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Data_Record__c</fullName>
        <label>GRAX Data Record</label>
        <referenceTo>GRAX_Data_Record__c</referenceTo>
        <relationshipLabel>GRAX Data Record Ids</relationshipLabel>
        <relationshipName>GRAX_Data_Record_Ids</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To be Deleted</fullName>
                </value>
                <value>
                    <fullName>Deleted with Master Parent</fullName>
                </value>
                <value>
                    <fullName>Successfully Deleted</fullName>
                </value>
                <value>
                    <fullName>Delete Error</fullName>
                </value>
                <value>
                    <fullName>Sent to GRAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Data Record Id</label>
    <nameField>
        <displayFormat>GRAX-RecId-{000000000}</displayFormat>
        <label>GRAX Data Record Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Record Ids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Archive</description>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Field__c</fullName>
        <description>Date_Field</description>
        <inlineHelpText>Salesforce field on the selected object from which the Start &amp; End Dates are being used</inlineHelpText>
        <label>Date Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Run_Date__c</fullName>
        <description>Next_Run_Date</description>
        <inlineHelpText>Next date/time this Scheduled Process will execute</inlineHelpText>
        <label>Next Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object_Name</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <description>Schedule_Type</description>
        <inlineHelpText>Frequency of when the Scheduled Process will run</inlineHelpText>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Once</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors sending data</fullName>
                </value>
                <value>
                    <fullName>Sending data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Deleting Salesforce records</fullName>
                </value>
                <value>
                    <fullName>Pending send data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors deleting records</fullName>
                </value>
                <value>
                    <fullName>Starting Archive Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Start_Datetime__c</fullName>
        <inlineHelpText>Date/Time from the field value in the &quot;Date Field&quot; from when this Scheduled Process will begin.</inlineHelpText>
        <label>Target Start Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Records_Errors__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Records Errors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hierarchy</fullName>
                    <default>true</default>
                    <label>Hierarchy</label>
                </value>
                <value>
                    <fullName>Multi-Object</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXBatchToResendDataRecordsTest.cls
/*****************************************************************************************
Name              : GRAXBatchToResendDataRecordsTest
Description       : 
Revision History  :
Created/Modified by   Created/Modified Date     Requested by        Related Task/Issue     
----------------------------------------------------------------------------------------
1. Leandro Brunner       	04/17/2018			David Mackey        https://app.asana.com/0/326600806074978/633149554508924/f
2. Ariel Yankelevich     	03/14/2019         	David Mackey        Oak North Issues (https://app.asana.com/0/326600806074978/1114340491893894/f)
3. Nicolas Ralero		 	04/11/2019			David Mackey		GRAX Archive Error Message (https://app.asana.com/0/326600806074978/1117627231071642/f)
4. Ariel Yankelevich     	05/07/2019          David Mackey        Remove Reference to GRAX Query Object (https://app.asana.com/0/326600806074978/1121760476564626/f)
******************************************************************************************/
@isTest
private class GRAXBatchToResendDataRecordsTest {
    
    @isTest(seeAllData = false)
    static void GRAXBatchToResendDataRecordsTest() {
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(1);
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        gsp.type__c = 'Multi-Object';
        gsp.Status__c = 'Pending send data to GRAX';
        insert gsp;
        
        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.GRAX_Schedule_Process__c = gsp.Id;
		dr.Salesforce_Object__c = 'Test';
		dr.Status__c = 'Error';
		dr.of_Times_Sent__c = 4;

        GRAX_Data_Record__c dr2 = new GRAX_Data_Record__c();
        dr2.GRAX_Schedule_Process__c = gsp.Id;
		dr2.Salesforce_Object__c = 'Test';
		dr2.Status__c = 'Error';
		dr2.of_Times_Sent__c = 5;

		insert new List<GRAX_Data_Record__c> { dr, dr2 };

		Attachment att = new Attachment();
		att.Name = 'request.txt';
		att.Body = Blob.valueOf('{}');
		att.ParentId = dr.Id;

        Attachment att2 = new Attachment();
		att2.Name = 'request.txt';
		att2.Body = Blob.valueOf('{}');
		att2.ParentId = dr2.Id;

        insert new List<Attachment> { att, att2 };

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, '{"message": "Test successful"}', 'http://test.grax.io/applications/neo4j/configure', null);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        database.executebatch(new GRAXBatchToResendDataRecords());

        Test.stopTest();

        Map<Id, GRAX_Data_Record__c> dataRecords2Check = new Map<Id, GRAX_Data_Record__c>([SELECT Id, Status__c, of_Times_Sent__c, Error_Message__c FROM GRAX_Data_Record__c]);

        System.assertEquals(5, dataRecords2Check.get(dr.Id).of_Times_Sent__c);
        System.assertEquals(null, dataRecords2Check.get(dr.Id).Error_Message__c);
        System.assertEquals('Sent Successful', dataRecords2Check.get(dr.Id).Status__c);

        System.assertEquals(5, dataRecords2Check.get(dr2.Id).of_Times_Sent__c);
        System.assertEquals('Error', dataRecords2Check.get(dr2.Id).Status__c);
    }
    
    @isTest(seeAllData = false)
    static void GRAXBatchToResendDataRecordsTest2() {
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(1);
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        gsp.type__c = 'Multi-Object';
        gsp.Status__c = 'Pending send data to GRAX';
        gsp.Execution_Unique_Key__c = 'testUniqueKey';
        insert new List<GRAX_Schedule_Process__c>{gsp};
        
        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.GRAX_Schedule_Process__c = gsp.Id;
		dr.Salesforce_Object__c = 'Test';
		dr.Status__c = 'Processing';
		dr.Execution_Unique_Key__c = gsp.Execution_Unique_Key__c;
		dr.of_Times_Sent__c = 4;

        GRAX_Data_Record__c dr2 = new GRAX_Data_Record__c();
        dr2.GRAX_Schedule_Process__c = gsp.Id;
		dr2.Salesforce_Object__c = 'Test';
		dr2.Status__c = 'Error';
		dr2.Execution_Unique_Key__c = gsp.Execution_Unique_Key__c;
		dr2.of_Times_Sent__c = 4;

		insert new List<GRAX_Data_Record__c> { dr, dr2 };
		
		GRAX_Data_Record_Id__c dri1 = new GRAX_Data_Record_Id__c(GRAX_Data_Record__c = dr.Id);
        insert new List<GRAX_Data_Record_Id__c>{dri1};
		
		dr.Status__c = 'Error';
		dr.of_Times_Sent__c = 5;
		update new List<GRAX_Data_Record__c> { dr };
		
		Map<Id, GRAX_Schedule_Process__c> gsp2Check = new Map<Id, GRAX_Schedule_Process__c>([SELECT Id, Total_Records_Errors__c FROM GRAX_Schedule_Process__c WHERE Id IN :new List<GRAX_Schedule_Process__c>{gsp}]);
		System.assertEquals(1, gsp2Check.get(gsp.Id).Total_Records_Errors__c);

		Attachment att = new Attachment();
		att.Name = 'request.txt';
		att.Body = Blob.valueOf('{}');
		att.ParentId = dr.Id;

        Attachment att2 = new Attachment();
		att2.Name = 'request.txt';
		att2.Body = Blob.valueOf('{}');
		att2.ParentId = dr2.Id;

        insert new List<Attachment> { att, att2 };

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, '{"message": "Test successful"}', 'http://test.grax.io/applications/neo4j/configure', null);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        GRAXBatchToResendDataRecords b = new GRAXBatchToResendDataRecords();
        b.currentJobId = gsp.Id;
        b.isExecuteNow = true;
        database.executebatch(b);

        Test.stopTest();

        gsp2Check = new Map<Id, GRAX_Schedule_Process__c>([SELECT Id, Status__c FROM GRAX_Schedule_Process__c WHERE Id IN :new List<GRAX_Schedule_Process__c>{gsp}]);        
        System.assertEquals('Completed - Errors sending data', gsp2Check.get(gsp.Id).Status__c);
    }
    
    @isTest(seeAllData = false)
    static void GRAXBatchToResendDataRecordsTest3(){
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(1);
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        gsp.type__c = 'Hierarchy';
        gsp.Status__c = 'Running';
        insert gsp;

		Attachment att1 = new Attachment(ParentId = gsp.Id, Name = 'DelayedGraxDataRecordIdsToUpdateStatus.txt', Body = Blob.valueOf(JSON.serialize(new List<String>{'12345'})));
		insert new List<Attachment>{att1};

		GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.GRAX_Schedule_Process__c = gsp.Id;
		dr.Salesforce_Object__c = 'Test';
		dr.Status__c = 'Error';
		dr.of_Times_Sent__c = 4;

        GRAX_Data_Record__c dr2 = new GRAX_Data_Record__c();
        dr2.GRAX_Schedule_Process__c = gsp.Id;
		dr2.Salesforce_Object__c = 'Test';
		dr2.Status__c = 'Error';
		dr2.of_Times_Sent__c = 5;

		insert new List<GRAX_Data_Record__c> { dr, dr2 };

		Attachment att = new Attachment();
		att.Name = 'request.txt';
		att.Body = Blob.valueOf('{}');
		att.ParentId = dr.Id;

        Attachment att2 = new Attachment();
		att2.Name = 'request.txt';
		att2.Body = Blob.valueOf('{}');
		att2.ParentId = dr2.Id;

        insert new List<Attachment> { att, att2 };

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, '{"message": "Test successful"}', 'http://test.grax.io/applications/neo4j/configure', null);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);        
		database.executebatch(new GRAXBatchToResendDataRecords());

        Test.stopTest();

		Attachment attachment2Check = [SELECT Id, Body FROM Attachment WHERE Id = : att1.Id];
		System.assert(attachment2Check.Body.toString().contains(dr.Id));
	}

	@isTest(seeAllData = false)
    static void GRAXBatchToResendDataRecordsTest4(){
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = GRAXUtils.getNameSpacePrefix() + 'GRAX_Schedule_Process__c';
        gsp.Date_Field__c = 'LastModifiedDate';
        gsp.Target_Start_Datetime__c = Date.today().addDays(1);
        gsp.Schedule_Type__c = 'Once';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = false;
        gsp.type__c = 'Hierarchy';
        gsp.Status__c = 'Pending send data to GRAX';
        insert gsp;

		GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.GRAX_Schedule_Process__c = gsp.Id;
		dr.Salesforce_Object__c = 'Test';
		dr.Status__c = 'Error';
		dr.of_Times_Sent__c = 4;

        GRAX_Data_Record__c dr2 = new GRAX_Data_Record__c();
        dr2.GRAX_Schedule_Process__c = gsp.Id;
		dr2.Salesforce_Object__c = 'Test';
		dr2.Status__c = 'Error';
		dr2.of_Times_Sent__c = 5;

		insert new List<GRAX_Data_Record__c> { dr, dr2 };

		Attachment att1 = new Attachment(ParentId = gsp.Id, Name = 'DelayedGraxDataRecordIdsToUpdateStatus.txt', Body = Blob.valueOf(JSON.serialize(new List<String>{dr.Id, dr2.Id})));
		insert new List<Attachment>{att1};

		Attachment att = new Attachment();
		att.Name = 'request.txt';
		att.Body = Blob.valueOf('{}');
		att.ParentId = dr.Id;

        Attachment att2 = new Attachment();
		att2.Name = 'request.txt';
		att2.Body = Blob.valueOf('{}');
		att2.ParentId = dr2.Id;

        insert new List<Attachment> { att, att2 };

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, '{"message": "Test successful"}', 'http://test.grax.io/applications/neo4j/configure', null);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);		
		database.executebatch(new GRAXBatchToResendDataRecords());

        Test.stopTest();

		Map<Id, GRAX_Data_Record__c> dataRecords2Check = new Map<Id, GRAX_Data_Record__c>([SELECT Id, Status__c, of_Times_Sent__c, Error_Message__c FROM GRAX_Data_Record__c]);
        
        System.assertEquals(null, dataRecords2Check.get(dr.Id).Error_Message__c);
        System.assertEquals('Sent Successful', dataRecords2Check.get(dr.Id).Status__c);
        
        System.assertEquals('Error', dataRecords2Check.get(dr2.Id).Status__c);
    }
}