metadata/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>This object is related to the GRAX Schedule Process Object. These records contain the object and relationship to the Salesforce record(s) which will be backed up/archived from Salesforce.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sched_Proc_Hierarchy_Unique_Key__c</fullName>
        <description>Sched_Proc_Hierarchy_Unique_Key</description>
        <label>Sched Proc Hierarchy Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAX_Data_Record_Id__c.object
<CustomObject>
    <description>This object contains the specific Salesforce record id which will be backed up/archived as part of the GRAX Scheduled process. These records are automatically deleted at the conclusion of a successful GRAX Scheduled Process.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_Data_Record__c</fullName>
        <label>GRAX Data Record</label>
        <referenceTo>GRAX_Data_Record__c</referenceTo>
        <relationshipLabel>GRAX Data Record Ids</relationshipLabel>
        <relationshipName>GRAX_Data_Record_Ids</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processed_Child_Index__c</fullName>
        <description>Processed_Child_Index</description>
        <label>Processed Child Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFDC_Id__c</fullName>
        <description>SFDC_Id</description>
        <label>SFDC Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>GRAX Data Record Id</label>
    <nameField>
        <displayFormat>GRAX-RecId-{000000000}</displayFormat>
        <label>GRAX Data Record Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Record Ids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Execution_Unique_Key__c</fullName>
        <label>Execution Unique Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progressive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Progressive</label>
        <type>Checkbox</type>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXBatchToGetSchedJobParentRecords.cls
/*****************************************************************************************
Name              : GRAXBatchToGetSchedJobParentRecords
Description       : This batch process gets the list of every SFDC Parent Id that was already processed in a previous iteration of the main batch in a Hierarchy GRAX Schedule Process context
Revision History  :
Created/Modified by   Created/Modified Date     Requested by          Related Task/Issue             
----------------------------------------------------------------------------------------
1. Nicolas Ralero	     04/18/2018           	David Mackey        GRAX Archive Error Message (https://app.asana.com/0/326600806074978/1117627231071642/f)
2. Ariel Yankelevich     04/26/2019           	David Mackey        GRAX Archive Error Message (https://app.asana.com/0/326600806074978/1117627231071642/f)
3. Ariel Yankelevich	 04/22/2019           	David Mackey        Internal Salesforce Error: moving job from FlexQueue to MQ failed (https://app.asana.com/0/326600806074978/1118660079719637/f)
4. Ariel Yankelevich	 05/13/2019				David Mackey		Optichains Prod Backup Issues (https://app.asana.com/0/326600806074978/1122687086503529/f)
******************************************************************************************/

public class GRAXBatchToGetSchedJobParentRecords implements Database.Batchable<sObject>, Database.Stateful {
	public String query = '';
	public List<Id> parentIds2ProcessForChild;
	public GRAXBatchToProcessSchedJob mainBatchProcess;
    
    
    public GRAXBatchToGetSchedJobParentRecords(GRAXBatchToProcessSchedJob mainBatchProcess){
        this.mainBatchProcess = mainBatchProcess;
        this.parentIds2ProcessForChild = new List<Id>();
        
        // Get the current child object structure
		GRAXBackupCtrl.ObjRelStructure sObjRelStruc = this.mainBatchProcess.objects2Process[this.mainBatchProcess.currentElementIndex];

		// Get the parent record Ids that still haven't been processed
		query = 'SELECT Id, SFDC_Id__c FROM GRAX_Data_Record_Id__c WHERE';
		query += ' ((Processed_Child_Index__c < ' + this.mainBatchProcess.currentElementIndex + ' AND Execution_Unique_Key__c = \'' + this.mainBatchProcess.executionUniqueKey + '\')';
		query += ' OR (GRAX_Data_Record__r.GRAX_Schedule_Process__r.Progressive__c = true AND Execution_Unique_Key__c <> \'' + this.mainBatchProcess.executionUniqueKey + '\'))';
		query += ' AND GRAX_Data_Record__r.GRAX_Schedule_Process__c = \'' + this.mainBatchProcess.currentJobId + '\'';
		query += ' AND GRAX_Data_Record__r.Sched_Proc_Hierarchy_Unique_Key__c = \'' + sObjRelStruc.parentUniqueKey + '\'';
		query += ' LIMIT ' + GRAXUtils.getMaxNumberOfParentsOnHierarchyBackup(sObjRelStruc.name);
		
		System.debug('The SOQL query is: ' + query);
    }
	
	public Database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

	public void execute(Database.BatchableContext BC, List<GRAX_Data_Record_Id__c> scope){
		List<GRAX_Data_Record_Id__c> graxDataRecs2Up = new List<GRAX_Data_Record_Id__c>();
	            
        for(GRAX_Data_Record_Id__c grxDRId : scope){
            this.parentIds2ProcessForChild.add(grxDRId.SFDC_Id__c);
            
            // Flag all the parent Ids that are going to be processed during this execution
            grxDRId.Processed_Child_Index__c = this.mainBatchProcess.currentElementIndex;
            grxDRId.Execution_Unique_Key__c = this.mainBatchProcess.executionUniqueKey;
            graxDataRecs2Up.add(grxDRId);
        }
        
        if(graxDataRecs2Up.size() > 0){
            update graxDataRecs2Up;
        }
	}

	public void finish(Database.BatchableContext BC){
		// Continue the batch execution for the current object being process using all its parents
		this.mainBatchProcess.parentIds2ProcessForChild = this.parentIds2ProcessForChild;
		String nextJobId = this.mainBatchProcess.executeNextBatchRun(this.mainBatchProcess);
		
		if(GRAXSchedulerToProcessSchedJobs.isEmptyId(nextJobId)) {
			try{
				// Add a GRAX Log in case the batch job cannot get into the Queue
				throw new GRAXException('This SF environment has reached its maximum number of concurrent records in the APEX Flex Queue. Please try scheduling again. GRAX Schedule Process Id: \'' + this.mainBatchProcess.currentJobId + '\'', 0);
			}catch(Exception e){
				GRAXLogs.addLogException(e, 'APEX Class: GRAXBatchToGetSchedJobParentRecords, Method: finish.');
			}
		}
	}
}