metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Is_Running__c</fullName>
        <description>Field used to determine if the current Scheduled Process is in a &quot;running&quot; state</description>
        <formula>ISPICKVAL (Status__c, &quot;Running&quot;)  ||
ISPICKVAL (Status__c, &quot;Sending data to GRAX&quot;)  ||
ISPICKVAL (Status__c, &quot;Deleting Salesforce records&quot;)  ||
ISPICKVAL (Status__c, &quot;Pending send data to GRAX&quot;)  ||
ISPICKVAL (Status__c, &quot;Starting Archive Process&quot;)</formula>
        <label>Is Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <label>JobId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Run_Date__c</fullName>
        <description>Next_Run_Date</description>
        <inlineHelpText>Next date/time this Scheduled Process will execute</inlineHelpText>
        <label>Next Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object_Name</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors sending data</fullName>
                </value>
                <value>
                    <fullName>Sending data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Deleting Salesforce records</fullName>
                </value>
                <value>
                    <fullName>Pending send data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors deleting records</fullName>
                </value>
                <value>
                    <fullName>Starting Archive Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Report__c</fullName>
        <inlineHelpText>ID of the Salesforce report used for this process</inlineHelpText>
        <label>Target Report</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Objects_Processed__c</fullName>
        <label>Total Objects Processed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Objects_To_Process__c</fullName>
        <label>Total Objects To Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>currentElementIndex__c</fullName>
        <label>currentElementIndex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hierarchy</fullName>
                    <default>true</default>
                    <label>Hierarchy</label>
                </value>
                <value>
                    <fullName>Multi-Object</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXSchedulerToProcessSchedJobs.cls
/*****************************************************************************************
Name              : GRAXSchedulerToProcessSchedJobs
Description       : This Schedule process finds the Schedule Process jobs that are supposed to run at this moment or did not execute in the previous Schedule execution
Revision History  :
Created/Modified by   Created/Modified Date     Requested by          Related Task/Issue             
----------------------------------------------------------------------------------------
1. Ariel Yankelevich       05/08/2018           David Mackey        GRAX Audit Trail Process (https://app.asana.com/0/326600806074978/633149554508926/f)
2. Ariel Yankelevich       07/18/2018           David Mackey        Multi-Object Backup (https://app.asana.com/0/326600806074978/743044564916005/f)
3. Leandro Brunner         08/07/2018           David Mackey        Agco Fixes (https://app.asana.com/0/326600806074978/770976244463043/f)
4. Leandro Brunner         08/22/2018           David Mackey        Initial Backup updates (https://app.asana.com/0/326600806074978/788118599521250/f)
5. Ariel Yankelevich       10/11/2018           David Mackey        Minor Updates (https://app.asana.com/0/326600806074978/857103514581849/f)
6. Leandro Brunner         12/26/2018           David Mackey        Backup/Archive UI Updates (https://app.asana.com/0/326600806074978/950283827722121/f)
7. Leandro Brunner         02/26/2019           David Mackey        Update Backup Process (https://app.asana.com/0/326600806074978/1109887667389108/f)
8. Ariel Yankelevich       03/22/2019           David Mackey        Oak North Updates #2 (https://app.asana.com/0/326600806074978/1114502823954369/f)
9. Ariel Yankelevich       04/03/2019           David Mackey        Latest Package Bugs (https://app.asana.com/0/326600806074978/1117046362603242/f)
10. Ariel Yankelevich      04/17/2019           David Mackey        GRAX Archive Error Message (https://app.asana.com/0/326600806074978/1117627231071642/f)
11. Sergio Caputo		   04/17/2019           David Mackey        GRAXSchedulerToProcessSchedJobs Error (https://app.asana.com/0/326600806074978/1118862586802334/f)
12. Ariel Yankelevich	   04/22/2019           David Mackey        Internal Salesforce Error: moving job from FlexQueue to MQ failed (https://app.asana.com/0/326600806074978/1118660079719637/f)
13. Ariel Yankelevich	   05/13/2019           David Mackey        Optichains Prod Backup Issues (https://app.asana.com/0/326600806074978/1122687086503529/f)
******************************************************************************************/
global class GRAXSchedulerToProcessSchedJobs implements Schedulable {
    public static void enqueueSchedule(GRAX_Schedule_Process__c schedProcess, Boolean isExecuteNow) {
        try {
            if(Limits.getQueueableJobs() <> Limits.getLimitQueueableJobs()) {
            	// First update the Status of the Schedule Job to "Running" in order to fire the triggers before executing the job
                schedProcess.Status__c = 'Running';
                update schedProcess;
            	
                System.enqueueJob(new AsyncExecToProcessSchedJobs(schedProcess, isExecuteNow));
            }
        } catch(Exception e) {
            System.debug(e);
        }
    }
    
    global void execute(SchedulableContext sc) {
        Map<String, GRAX_Schedule_Process__c> schedulesToCheckByJobId = new Map<String, GRAX_Schedule_Process__c>();

        // Find any Schedule Process Job that is supposed to run at the current GMT time, 
        // or that it hasn't been executed on the previous Schedule run and it's not currently executing
        for(GRAX_Schedule_Process__c schedProcess : [SELECT Id, Status__c, Is_Running__c, JobId__c FROM GRAX_Schedule_Process__c WHERE ((Next_Run_Date__c <= :System.now() AND Is_Running__c = false) OR (Status__c = 'Running' AND JobId__c <> null))]){
            if(!schedProcess.Is_Running__c) {
                enqueueSchedule(schedProcess, true);
            } else if(schedProcess.Status__c == 'Running' && !String.isBlank(schedProcess.JobId__c)){
                schedulesToCheckByJobId.put(schedProcess.JobId__c.substring(0, 15), schedProcess);
                
                if(GRAXSchedulerToProcessSchedJobs.isEmptyId(schedProcess.JobId__c)){
                	// Last attempt to execute the batch failed because of the APEX Flex Queue being full
                	schedulesToCheckByJobId.remove(schedProcess.JobId__c);
                	enqueueSchedule(schedProcess, false);
                }
            }
        }
		
		if(schedulesToCheckByJobId.size() > 0){
	        for(AsyncApexJob aaj : [SELECT Id, Status FROM AsyncApexJob WHERE Id IN :schedulesToCheckByJobId.keySet() AND Status = 'Failed']) {
	            enqueueSchedule(schedulesToCheckByJobId.get(String.valueOf(aaj.Id).substring(0, 15)), false);
	        }
		}
    }

    public class AsyncExecToProcessSchedJobs implements Queueable, Database.AllowsCallouts {
        private GRAX_Schedule_Process__c schedProcess;
        private Boolean isExecuteNow;

        public AsyncExecToProcessSchedJobs() {}
        public AsyncExecToProcessSchedJobs(GRAX_Schedule_Process__c schedProcess, Boolean isExecuteNow) {
            this.schedProcess = schedProcess;
            this.isExecuteNow = isExecuteNow;
        }

        public void execute(QueueableContext context) {
            try {
                String jobId;
                
                this.schedProcess = [SELECT Id, Status__c, Target_Report__c, Object_Name__c, Type__c, CurrentElementIndex__c, JobId__c, (SELECT Id FROM Attachments WHERE Name = 'SelectionJSON.txt' LIMIT 1) FROM GRAX_Schedule_Process__c WHERE Id =: this.schedProcess.Id];
                
                if(this.schedProcess.Attachments == null || this.schedProcess.Attachments.size() == 0){
                    throw new GRAXException('The GRAX Scheduled Process has not been created correctly. Please ensure that the Scheduled Process was created through the \'Create\' button on the \'Schedule\' tab. GRAX Schedule Process Id: \'' + schedProcess.Id + '\'', 0);
                }
                
                Integer currentIndex = 0;
                if(this.schedProcess.CurrentElementIndex__c <> null && this.schedProcess.JobId__c <> null && !this.isExecuteNow) {
                    // We need to continue the process from the object index that is failed the batch execution
                    currentIndex = schedProcess.currentElementIndex__c.intValue();
                }
                
                // Only fire the Hierarchy Schedule Process based on a Report, if the currentIndex == 0
                if(schedProcess.Target_Report__c <> null && currentIndex == 0) {
                    GRAXBatchToProcessSchedJobFromReport b = new GRAXBatchToProcessSchedJobFromReport(schedProcess.Id, null, null, isExecuteNow);
                    schedProcess.Total_Objects_To_Process__c = b.mainBatchProcess.objects2Process.size();
                    if(!Test.isRunningTest()) jobId = String.valueOf(Database.executebatch(b, GRAXUtils.getBatchMaxExecutionNumber(schedProcess.Object_Name__c)));
                }else{
                    // 'Multi-Object' or Date criteria backups
                    GRAXBatchToProcessSchedJobMainObject b = new GRAXBatchToProcessSchedJobMainObject(schedProcess.Id, isExecuteNow, schedProcess.Type__c == 'Multi-Object', currentIndex);
                    schedProcess.Total_Objects_To_Process__c = b.mainBatchProcess.objects2Process.size();
                    if(!Test.isRunningTest()) jobId = String.valueOf(Database.executebatch(b, GRAXUtils.getBatchMaxExecutionNumber(schedProcess.Object_Name__c)));
                }

                // Check that the Batch Job made it to the APEX Flex Queue
                if(!String.isEmpty(jobId) && !GRAXSchedulerToProcessSchedJobs.isEmptyId(jobId)) {
                	schedProcess.JobId__c = jobId;
                	schedProcess.Total_Objects_Processed__c = currentIndex;
                	update schedProcess;
                }else{
                	// Set the Status to "Error" in case the batch job cannot get into the Queue
                	throw new GRAXException('This SF environment has reached its maximum number of concurrent records in the APEX Flex Queue. Please try scheduling again. GRAX Schedule Process Id: \'' + schedProcess.Id + '\'', 0);
                }
            } catch(Exception e) {
                GRAXLogs.addLogException(e);
                           
                schedProcess.Status__c = 'Error';
                update schedProcess;
            }
        }
    }
    
    public static Boolean isEmptyId(String jobId){
    	return !String.isEmpty(jobId) && (jobId == '000000000000000' || jobId == '000000000000000AAA');
    }
}