metadata/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>This object is related to the GRAX Schedule Process Object. These records contain the object and relationship to the Salesforce record(s) which will be backed up/archived from Salesforce.</description>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Times_Sent__c</fullName>
        <description>of_Times_Sent</description>
        <label># of Times Sent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <description>This object is the record which will be executed to back up/archive records from Salesforce. This record contains the objects, schedule frequency, start time, etc. of the back up/archive process.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors sending data</fullName>
                </value>
                <value>
                    <fullName>Sending data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Deleting Salesforce records</fullName>
                </value>
                <value>
                    <fullName>Pending send data to GRAX</fullName>
                </value>
                <value>
                    <fullName>Completed - Errors deleting records</fullName>
                </value>
                <value>
                    <fullName>Starting Archive Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Records_Errors__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Records Errors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXBatchToReTrySendingDataRecords.cls
/*****************************************************************************************
Name              : GRAXBatchToReTrySendingDataRecords
Description       : Add a new Action in the Scheduled Job table when the status is 
					"Completed - Error Sending Data to GRAX" and then fire the batch process 
					which will set the variables to re-send the records which "completed with error".
Revision History  :
Created/Modified by   Created/Modified Date     Requested by          Related Task/Issue             
----------------------------------------------------------------------------------------
2. Nahuel Leiva            05/28/2019			David Mackey		  Constellation Prod Backup Issues (https://app.asana.com/0/326600806074978/1124574665749273/f)
******************************************************************************************/
public class GRAXBatchToReTrySendingDataRecords implements Database.Batchable<sObject>, Database.Stateful {
	public String query = '';
	public Id graxScheduledProcess;
	
	public GRAXBatchToReTrySendingDataRecords(Id scheduledProcessId){
		GRAX_Schedule_Process__c scheduleProcess = new GRAX_Schedule_Process__c(Id = scheduledProcessId, Status__c = 'Sending data to GRAX', Total_Records_Errors__c = 0);
		this.graxScheduledProcess = scheduledProcessId;
		update scheduleProcess;
	}
    public Database.QueryLocator start(Database.BatchableContext bc) {
    	query = 'SELECT Id, of_Times_Sent__c FROM GRAX_Data_Record__c WHERE GRAX_Schedule_Process__r.Id = \'' + graxScheduledProcess + '\'';
    	query += ' AND of_Times_Sent__c >= 5 AND Status__c = \'Error\'';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<GRAX_Data_Record__c> masterScope) {
    	List<GRAX_Data_Record__c> listDataRecord = new List<GRAX_Data_Record__c>();
        for (GRAX_Data_Record__c gdc : masterScope) {
        	GRAX_Data_Record__c newDataRecord = new GRAX_Data_Record__c(Id = gdc.Id, of_Times_Sent__c = 0);
        	listDataRecord.add(newDataRecord);
        }
        if (!listDataRecord.isEmpty()) {
        	update listDataRecord;
        }
    }
    
    public void finish(Database.BatchableContext BC) {
    	GRAXSchedulerToResendDataRecords.executeGRAXBatchToResendDataRecords();
    }
}