metadata/objects/GRAX_Dynamic_Flow_Trigger__mdt.object
<CustomObject>
    <fields>
        <fullName>Flow_Unique_Name__c</fullName>
        <label>Flow Unique Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progressive_Query__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Progressive Query?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOQL_Query__c</fullName>
        <label>SOQL Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>GRAX Dynamic Flow Trigger</label>
    <pluralLabel>GRAX Dynamic Flow Triggers</pluralLabel>
</CustomObject>

metadata/objects/GRAXQuery__c.object
<CustomObject>
    <description>This object is used to store the custom fields and filters used by GRAX Connect</description>
    <fields>
        <fullName>ObjectName__c</fullName>
        <externalId>true</externalId>
        <label>ObjectName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>GRAX : Object Configuration</label>
    <nameField>
        <displayFormat>GRAX-{000000}</displayFormat>
        <label>GRAXQueries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX : Object Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/GRAXBatchToProcessDynamicFlowTest.cls
/*****************************************************************************************
Name              : GRAXBatchToProcessDynamicFlowTest
Description       :
Revision History  :
Created/Modified by   Created/Modified Date     Requested by          Related Task/Issue             
----------------------------------------------------------------------------------------
1. Leandro Brunner         09/03/2018           David Mackey          Scheduled Job to Trigger a Flow (https://app.asana.com/0/326600806074978/778127037078388/f)
******************************************************************************************/
@isTest
public class GRAXBatchToProcessDynamicFlowTest {
    @isTest
    static void GRAXBatchToProcessDynamicFlowTest1() {
        GRAXQuery__c gq = new GRAXQuery__c();
        gq.ObjectName__c = 'GRAXQuery__c';
        insert gq;

        List<GRAX_Dynamic_Flow_Trigger__mdt> gdfTriggerList;

        String gdfTrigger1 = '';
        gdfTrigger1 += '{';
        gdfTrigger1 += '"Name": "gdfTrigger1",';
        gdfTrigger1 += '"Batch_Size__c": 1,';
        gdfTrigger1 += '"Flow_Unique_Name__c": "TestFlow",';
        gdfTrigger1 += '"Progressive_Query__c": false,';
        gdfTrigger1 += '"SOQL_Query__c": "SELECT Id FROM GRAXQuery__c"';
        gdfTrigger1 += '}';

        String gdfTrigger2 = '';
        gdfTrigger2 += '{';
        gdfTrigger2 += '"Name": "gdfTrigger2",';
        gdfTrigger2 += '"Batch_Size__c": 1,';
        gdfTrigger2 += '"Flow_Unique_Name__c": "TestFlow",';
        gdfTrigger2 += '"Progressive_Query__c": true,';
        gdfTrigger2 += '"SOQL_Query__c": "SELECT Id FROM GRAXQuery__c"';
        gdfTrigger2 += '}';


        String gdfTriggerListString = '[' + gdfTrigger1 + ',' + gdfTrigger2 + ']';

        gdfTriggerList = (List<GRAX_Dynamic_Flow_Trigger__mdt>) JSON.deserialize(gdfTriggerListString, List<GRAX_Dynamic_Flow_Trigger__mdt>.class);

        GRAXBatchToProcessDynamicFlow b = new GRAXBatchToProcessDynamicFlow(gdfTriggerList, 0);

        Test.startTest();

        Id jobId = Database.executebatch(b, 1);

        Test.stopTest();
    }
}